// flow-typed signature: 5590a1389e5fab4f62f8ddb722b5ff3d
// flow-typed version: <<STUB>>/level_v^3.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'level'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'level' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'level/level' {
  declare module.exports: any;
}

declare module 'level/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'level/level.js' {
  declare module.exports: $Exports<'level/level'>;
}
declare module 'level/test.js' {
  declare module.exports: $Exports<'level/test'>;
}
